#!/usr/bin/env node

const port = 3333;

var util = require('util');

var http = require('http'),
    finalhandler = require('finalhandler'),
    serveStatic = require('serve-static'),
    serve = serveStatic('build/web');

var server = http.createServer(function(req, res) {
  var done = finalhandler(req, res);
  serve(req, res, done);
});
  
server.listen(port);
console.log('Webserver running locally at http://localhost:' + port);

var ngrok = require('ngrok');
 
ngrok.connect(port, function (err, url) {
  if (err) {
    console.log('Error: ' + util.inspect(err));
  }
  if (url) {
    console.log('Webserver running publicly at ' + url);
  }
});
